# IS 362 – Week 5 Assignment
### Nicholas Ileczko
Your task in this week’s assignment is to answer three questions:
1. What is the northernmost airport in the United States?

2. What is the easternmost airport in the United States?

3. On February 12th, 2013, which New York area airport had the windiest weather?

Being successful on this assignment requires using both:  
* Your developing skills in Python and pandas, and
* Your research skills in validating your candidate answers in context

https://github.com/hadley/nycflights13/tree/master/data-raw

What is the northernmost airport in the United States?

In [4]:
#importing pandas and numpy
import pandas as pd
import numpy as np
#retrieving csv from github user hadley
airports = pd.read_csv('https://raw.githubusercontent.com/hadley/nycflights13/master/data-raw/airports.csv')
#processing data to get answer, displaying 5 

airports.sort_values(by = 'lat', ascending = False).head(5)

,faa,name,lat,lon,alt,tz,dst,tzone
417,EEN,Dillant Hopkins Airport,72.270833,42.898333,149,-5.0,A,\N
230,BRW,Wiley Post Will Rogers Mem,71.285446,-156.766003,44,-9.0,A,America/Anchorage
110,AIN,Wainwright Airport,70.638056,-159.994722,41,-9.0,A,America/Anchorage
708,K03,Wainwright As,70.613378,-159.860350,35,-9.0,A,America/Anchorage
152,ATK,Atqasuk Edward Burnell Sr Memorial Airport,70.467300,-157.436000,96,-9.0,A,America/Anchorage

According to this list, Dillan Hopkins Airport is the nothernmost airport in the United States.
But according to this wikipeida article: 
https://en.wikipedia.org/wiki/Wiley_Post%E2%80%93Will_Rogers_Memorial_Airport
It is Willey Post WIll Rogers Memorial Airport

What is the easternmost airport in the United States?

In [6]:
#retrieving csv from github user hadley
ea = pd.read_csv('https://raw.githubusercontent.com/hadley/nycflights13/master/data-raw/airports.csv')

northeast_airports = ea[(ea['lat'] > 44) & (ea['lat'] <= 50) & (ea['lon'] >= -75) & (ea['lon'] <= -65)]
northeast_airports.sort_values('lon', ascending=False).head(5)

,faa,name,lat,lon,alt,tz,dst,tzone
444,EPM,Eastport Municipal Airport,44.910111,-67.012694,45,-5.0,A,America/New_York
624,HUL,Houlton Intl,46.123083,-67.792056,489,-5.0,A,America/New_York
259,CAR,Caribou Muni,46.871500,-68.017917,626,-5.0,A,America/New_York
1101,PQI,Northern Maine Rgnl At Presque Isle,46.688958,-68.044797,534,-5.0,A,America/New_York
1398,WFK,Northern Aroostook Regional Airport,47.285556,-68.312778,988,-5.0,A,America/New_York

The easternmost airport in the United States is Eastport Municipal Airport.
This can be confirmed here: 
http://www.answers.com/Q/What_is_the_Easternmost_airport_in_US?#slide=2

On February 12th, 2013, which New York area airport had the windiest weather?

In [12]:
wind = pd.read_csv("https://raw.githubusercontent.com/hadley/nycflights13/master/data-raw/weather.csv")
wind[(wind["month"]==2) & (wind["day"]==12) & (wind["year"]==2013)].sort_values(by=["wind_speed"], ascending=False).head(5)

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
1015,EWR,2013,2,12,8,39.02,26.96,61.63,260.0,1048.36058,1206.432388,0.0,1008.3,10.0,2013-02-12T08:00:00Z
18433,LGA,2013,2,12,7,42.98,26.06,50.94,290.0,23.01560,26.485892,0.0,1007.1,10.0,2013-02-12T07:00:00Z
1024,EWR,2013,2,12,17,44.06,26.06,48.87,270.0,21.86482,25.161598,0.0,1012.5,10.0,2013-02-12T17:00:00Z
18444,LGA,2013,2,12,18,44.06,23.00,43.02,300.0,21.86482,25.161598,0.0,1011.7,10.0,2013-02-12T18:00:00Z
9728,JFK,2013,2,12,13,42.08,24.08,48.56,280.0,20.71404,23.837303,0.0,1011.6,10.0,2013-02-12T13:00:00Z

On February 12th, 2013 EWR had the windiest weather. 
Although according to this website the max mph was 37. So the data reading may be off. 
https://www.wunderground.com/history/airport/KEWR/2013/11/12/DailyHistory.html?req_city=Newark+International&req_state=NJ&req_statename=New+Jersey&reqdb.zip=07114&reqdb.magic=5&reqdb.wmo=99999